### ISSUE TITLE
Error in readme? 

### ISSUE THREAD

**Issue by clambin** [agence-gaya/traefik-plugin-blockuseragent#4]
Hey, just found your plugin, which was exactly what I needed. Thanks!

I did have some trouble getting it to work:  I think there's an error in the static config in the readme:

```
[experimental.plugins.blockuseragent]
    modulename = "github.com/traefik/plugin-blockuseragent"
    version = "v0.0.1"
```

Module name should be `github.com/agence-gaya/traefik-plugin-blockuseragent`, right?  And version should be whatever the latest version is (ie v0.1.7 for now)?

**Comment by jliebert** [comment]
Documentation updated, thanks.
