### ISSUE TITLE
Latest version IP log issue

### ISSUE THREAD

**Issue by slimshizn** [agence-gaya/traefik-plugin-blockuseragent#6]
Hi,

With the latest update with the user agent block, the IP address works well. However when going through a proxy (Cloudflare for instance) it's showing the incorrect IP address. Is there a setting here that can be added to give the correct header/real ip etc?

Thanks!

**Comment by jliebert** [comment]
Hello,

You can try plugin: https://github.com/agence-gaya/traefik-plugin-cloudflare
They are a setup for this case.
If you have many service behind Cloudflare, or frequent restart, I recommand to not use automatic cloudflare ip pull, is it fetched at each restart of the midleware, for each stack, if it failed your stack will not work. So add cloudflare ip manually in the setup.
In order put first the middleware traefik-plugin-cloudflare and after the others, they will log/use the true client ip.

Regards

**Comment by slimshizn** [comment]
Thank you for the reply, I'm guessing this will also work for any other CDN as well with the `trustedCIDRs`?

**Comment by slimshizn** [comment]
Tested working with 1 IP. Thank you for your help.

**Comment by slimshizn** [comment]
Disregard, unfortunately I was looking at a non CDN IP which went through correctly.

**Comment by slimshizn** [comment]
From what I can tell, it looks like the useragent plugin needs to support `X-Forwarded-For`.

**Comment by slimshizn** [comment]
I've opened a pull request, check it out and see if anything else needs to be altered. Thank you.

**Comment by jliebert** [comment]
Thanks for the PR, but it's the wrong way to get the IP of a client, you can't trust header like this to get IP of a client.
You need to setup correcly the revers proxy IP at traefik level, so traefik can trust them and provide right client ip adresse to middlewares.
